apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevirt-dra-driver-service-account
  namespace: kubevirt-dra-driver
  labels:
    app.kubernetes.io/name: kubevirt-dra-driver
    app.kubernetes.io/instance: kubevirt-dra-driver
